version: 2.1
jobs:
  build:
    working_directory: ~/toranoko-api-prototype
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: toranoko-api-prototype-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: toranoko-api-prototype-{{ checksum "pom.xml" }}
  test:
    working_directory: ~/toranoko-api-prototype
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn clean verify
      - store_test_results:
          path: target
      - store_artifacts:
          path: target

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
